// GVR Pharma IMS — Sample Seed Data
// Use seedFirestore.js to push this data into your Firestore database.

export const sampleMedicines = [
  {
    name:         "Paracetamol 500mg",
    category:     "Tablet",
    manufacturer: "Sun Pharma",
    stock:        120,
    price:        25,
    batchNumber:  "PARA001",
    expiryDate:   "2027-06-30",
    description:  "Common pain reliever and fever reducer",
  },
  {
    name:         "Amoxicillin 250mg",
    category:     "Capsule",
    manufacturer: "Cipla",
    stock:        10,
    price:        85,
    batchNumber:  "AMOX002",
    expiryDate:   "2025-09-15",
    description:  "Antibiotic for bacterial infections",
  },
  {
    name:         "Vitamin C Syrup",
    category:     "Syrup",
    manufacturer: "Abbott",
    stock:        5,
    price:        120,
    batchNumber:  "VITC003",
    expiryDate:   "2025-07-01",
    description:  "Immune system support",
  },
  {
    name:         "Metformin 500mg",
    category:     "Tablet",
    manufacturer: "USV",
    stock:        200,
    price:        45,
    batchNumber:  "MET004",
    expiryDate:   "2026-12-31",
    description:  "Diabetes management",
  },
  {
    name:         "Azithromycin 500mg",
    category:     "Tablet",
    manufacturer: "Zydus",
    stock:        0,
    price:        95,
    batchNumber:  "AZI005",
    expiryDate:   "2026-08-20",
    description:  "Antibiotic for respiratory infections",
  },
  {
    name:         "Cetirizine 10mg",
    category:     "Tablet",
    manufacturer: "Mankind",
    stock:        300,
    price:        15,
    batchNumber:  "CET006",
    expiryDate:   "2028-03-15",
    description:  "Antihistamine for allergies",
  },
  {
    name:         "Omeprazole 20mg",
    category:     "Capsule",
    manufacturer: "Sun Pharma",
    stock:        18,
    price:        60,
    batchNumber:  "OMP007",
    expiryDate:   "2026-11-30",
    description:  "Acid reflux treatment",
  },
  {
    name:         "Insulin Injection",
    category:     "Injection",
    manufacturer: "Novo Nordisk",
    stock:        50,
    price:        450,
    batchNumber:  "INS008",
    expiryDate:   "2025-08-10",
    description:  "Diabetes insulin therapy",
  },
  {
    name:         "Betadine Ointment",
    category:     "Ointment",
    manufacturer: "Win-Medicare",
    stock:        75,
    price:        110,
    batchNumber:  "BET009",
    expiryDate:   "2027-01-31",
    description:  "Antiseptic wound care",
  },
  {
    name:         "Ibuprofen 400mg",
    category:     "Tablet",
    manufacturer: "Cipla",
    stock:        12,
    price:        35,
    batchNumber:  "IBU010",
    expiryDate:   "2026-05-20",
    description:  "Anti-inflammatory pain relief",
  },
];
